package httpapi

import "net/http"

func (s *Server) registerRoutes(mux *http.ServeMux) {
	mux.HandleFunc("/health", s.healthHandler)
	mux.HandleFunc("/ready", s.readyHandler)
	mux.HandleFunc("/next-release", s.nextReleaseHandler)
	mux.HandleFunc("/suggest", s.suggestHandler)
	mux.HandleFunc("/trending", s.trendingHandler)
	mux.HandleFunc("/popular", s.popularHandler)
	mux.HandleFunc("/top-rated", s.topRatedHandler)
	mux.HandleFunc("/upcoming", s.upcomingHandler)
	mux.HandleFunc("/home", s.homeHandler)
	mux.HandleFunc("/search", s.searchHandler)
	mux.HandleFunc("/discover", s.discoverHandler)
	mux.HandleFunc("/details", s.detailsHandler)
	mux.HandleFunc("/person", s.personHandler)
	mux.HandleFunc("/person/recommend", s.personRecommendHandler)
	mux.HandleFunc("/bulk-next-release", s.bulkNextReleaseHandler)
	mux.HandleFunc("/saved", s.savedHandler)
	mux.HandleFunc("/saved/items", s.savedItemHandler)
	mux.HandleFunc("/achievements", s.achievementsHandler)
	mux.HandleFunc("/me", s.meHandler)
	mux.HandleFunc("/friends", s.friendsHandler)
	mux.HandleFunc("/friends/search", s.friendSearchHandler)
	mux.HandleFunc("/friends/requests", s.friendRequestsHandler)
	mux.HandleFunc("/friends/requests/respond", s.friendRequestRespondHandler)
	mux.HandleFunc("/friends/saved", s.friendSavedHandler)
	mux.HandleFunc("/friends/achievements", s.friendAchievementsHandler)
	mux.HandleFunc("/people/follows", s.peopleFollowsHandler)
	mux.HandleFunc("/recommendations/me", s.recommendationsHandler)
	mux.HandleFunc("/games/questions", s.gamesQuestionsHandler)
	mux.HandleFunc("/akinator/start", s.akinatorStartHandler)
	mux.HandleFunc("/akinator/next", s.akinatorNextHandler)
	mux.HandleFunc("/akinator/result", s.akinatorResultHandler)
	mux.HandleFunc("/jobs/akinator", s.akinatorJobHandler)
	mux.HandleFunc("/mood/questions", s.moodQuestionsHandler)
	mux.HandleFunc("/mood/next", s.moodNextHandler)
	mux.HandleFunc("/mood/picks", s.moodPicksHandler)
	mux.HandleFunc("/match/questions", s.matchQuestionsHandler)
	mux.HandleFunc("/match/picks", s.matchPicksHandler)
	mux.HandleFunc("/notifications", s.notificationsHandler)
	mux.HandleFunc("/notifications/read", s.notificationsReadHandler)
	mux.HandleFunc("/jobs/notifications", s.notificationsJobHandler)
	mux.HandleFunc("/auth/register", s.registerHandler)
	mux.HandleFunc("/auth/login", s.loginHandler)
	mux.HandleFunc("/auth/refresh", s.refreshHandler)
	mux.HandleFunc("/auth/logout", s.logoutHandler)
	mux.HandleFunc("/auth/verify", s.verifyEmailHandler)
	mux.HandleFunc("/auth/verify/resend", s.resendVerificationHandler)

	mux.Handle("/swagger/", http.StripPrefix("/swagger/", http.FileServer(http.Dir("./docs/swagger"))))
}
