export const copy = {
  appName: "DropDate",
  tagline: "Дата наступного релізу в один клік",
  hero: {
    eyebrow: "beta",
    webLead:
      "Вводиш назву — отримуєш дату наступного релізу. Простий спосіб не прогавити нову серію.",
    mobileLead:
      "Стеж за фільмами й серіалами. Показуємо, коли буде наступний реліз або нова серія.",
  },
  header: {
    searchPlaceholder: "Пошук...",
    searchOpenLabel: "Пошук",
    searchCloseLabel: "Закрити пошук",
    searchSubmit: "Знайти",
    searchBusy: "...",
    suggestionsLoading: "Підбираємо варіанти…",
    savedList: "Мій список",
  },
  sections: {
    trendingMovies: "Фільми зараз в тренді",
    trendingSeries: "Серіали зараз в тренді",
    trendingMoviesShort: "Фільми в тренді",
    trendingSeriesShort: "Серіали в тренді",
    recommendations: "Рекомендації",
    searchResults: "Усі результати",
    searchResultsTitle: "Результати пошуку",
    search: "Пошук",
    nextRelease: "Наступний реліз",
    similarTitles: "Схожі тайтли",
  },
  filters: {
    all: "Усі",
    movies: "Фільми",
    series: "Серіали",
    onlyMovies: "Лише фільми",
    onlySeries: "Лише серіали",
  },
  actions: {
    addToList: "Додати у список",
    inList: "У списку",
    added: "Додано",
    updateAll: "Оновити всі",
    updating: "Оновлюємо…",
    loadMore: "Показати ще",
  },
  lists: {
    follow: "Підписка",
    watchlist: "Want to watch",
    favorite: "Favorites",
    watched: "Переглянуто",
    disliked: "Не сподобалось",
    empty: "Поки порожньо — додай зі сторінки пошуку/трендів",
    loginPrompt: "Увійди, щоб зберігати більше та мати кілька списків.",
  },
  listStats: {
    total: "Всього у списку",
    thisWeek: "Цього тижня",
    watched: "Переглянуто",
    watchHours: "Годин у списку",
    avgRating: "Середня оцінка",
    rewatches: "Повторні перегляди",
    series: "Серіалів",
  },
  hints: {
    loadingCollection: "Завантажуємо підбірку…",
    loadingResults: "Завантажуємо…",
    loadingList: "Завантажуємо список…",
    loadingTitle: "Завантаження...",
    listEmpty:
      "Поки що порожньо. Додай перший тайтл через вкладку “Пошук”.",
    noRefresh: "Немає шоу для оновлення.",
    listUpdated: "Список оновлено.",
    noReleaseData: "Немає даних про реліз",
    noOverview: "Опис поки відсутній.",
    partialUpdate: (count: number) => `Частину шоу не оновлено (${count}).`,
  },
  errors: {
    invalidRequest: "Невірний запит.",
    detailsLoad: "Не вдалося завантажити деталі.",
    searchFailed: "Не вдалося отримати результати.",
    refreshFailed: "Не вдалося оновити список.",
    backendUnavailable: "Не вдалося зʼєднатись із бекендом",
    missingTitle: "Спочатку введи назву.",
    invalidJson: "Некоректна відповідь бекенду",
  },
  saved: {
    sectionTitles: {
      today: "Сьогодні",
      week: "Цього тижня",
      month: "Цього місяця",
      later: "Пізніше",
      ended: "Завершені",
      unknown: "Без дати",
    },
    removeAria: "Прибрати зі списку",
  },
  details: {
    labels: {
      type: "Тип",
      status: "Статус",
      date: "Дата",
      release: "Реліз",
      runtime: "Тривалість",
      seasonsEpisodes: "Сезони / епізоди",
      rating: "Рейтинг",
      votes: "Голосів",
      popularity: "Популярність",
      tmdbRating: "Рейтинг TMDB",
      detailsTitle: "Деталі",
      country: "Країна",
      genres: "Жанри",
      site: "Сайт",
      siteLink: "Перейти",
      nextEpisode: "Наступна серія",
      lastEpisode: "Остання серія",
      source: "Джерело",
      personalTitle: "Мій прогрес",
      yourRating: "Моя оцінка",
      watchCount: "Переглядів",
    },
    facts: {
      movie: "movie",
      series: "series",
      seasonsSuffix: "сезонів",
      episodesSuffix: "епізодів",
      minutesSuffix: "хв",
    },
  },
  search: {
    placeholder: "Наприклад, Dune",
    empty: "Нічого не знайдено.",
    emptyFull: "Нічого не знайдено. Спробуй іншу назву.",
    resultsCount: (count: number) => `Знайдено приблизно ${count} тайтлів`,
    searchingHint: "Зараз шукаємо підходящі варіанти",
  },
  mediaType: {
    movie: "Фільм",
    series: "Серіал",
  },
  misc: {
    dash: "—",
  },
  footer: {
    appStoreAlt: "Download on the App Store",
    playStoreAlt: "Get it on Google Play",
  },
  auth: {
    loginTitle: "Вхід",
    registerTitle: "Реєстрація",
    profile: "Профіль",
    signIn: "Увійти",
    signOut: "Вийти",
    emailLabel: "Email",
    passwordLabel: "Пароль",
    confirmPasswordLabel: "Повторіть пароль",
    emailPlaceholder: "you@example.com",
    passwordPlaceholder: "Пароль",
    confirmPasswordPlaceholder: "Повторіть пароль",
    submitLogin: "Увійти",
    submitRegister: "Створити акаунт",
    switchToRegister: "Створити акаунт",
    switchToLogin: "Вже є акаунт? Увійти",
    helperTitle: "Вимоги до пароля",
    helperText: "Мінімум 8 символів, великі/малі літери, цифра та спецсимвол.",
    errorGeneric: "Не вдалося виконати запит. Спробуй ще раз.",
    errorPasswordMismatch: "Паролі не збігаються.",
    loading: "Обробляємо…",
    closeLabel: "Закрити",
  },
};
